Traceback (most recent call last):
  File "/home/s1/tavangar/tavangar_simple/search_algorithm.py", line 24, in <module>
    import simple_utils
  File "/home/s1/tavangar/tavangar_simple/simple_utils.py", line 42, in <module>
    sim_population = cfg[survey]['sim_population']
KeyError: 'sim_population'

------------------------------------------------------------
Job <674579.0> was submitted from <des51.fnal.gov> by user <tavangar>.
Job was executed on host <des40.fnal.gov> as user <tavangar>.
</var/lib/condor/execute/dir_826842> was used as the initial working directory.
Results reported at Tue Jun  4 13:50:18 CDT 2019

Your job looked like:

------------------------------------------------------------
python /home/s1/tavangar/tavangar_simple/search_algorithm.py 340.31 -3.58 0.00 /home/s1/tavangar/tavangar_simple/decals_dr7_results/results_nside_32_6585.csv /home/s1/tavangar/tavangar_simple/decals_dr7_log/results_nside_32_6585.log
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

	Real time :			19.77 sec.
	CPU time :			2.08 sec.
	CPU percentage :		21%
	Max Memory :			279872 KB
	Average Memory :		0 KB

The output (if any) is above this job summary.
