Traceback (most recent call last):
  File "/home/s1/tavangar/tavangar_simple/search_algorithm.py", line 24, in <module>
    import simple_utils
  File "/home/s1/tavangar/tavangar_simple/simple_utils.py", line 42, in <module>
    sim_population = cfg[survey]['sim_population']
KeyError: 'sim_population'

------------------------------------------------------------
Job <673599.0> was submitted from <des51.fnal.gov> by user <tavangar>.
Job was executed on host <des40.fnal.gov> as user <tavangar>.
</var/lib/condor/execute/dir_791084> was used as the initial working directory.
Results reported at Tue Jun  4 13:36:52 CDT 2019

Your job looked like:

------------------------------------------------------------
python /home/s1/tavangar/tavangar_simple/search_algorithm.py 251.72 9.59 0.00 /home/s1/tavangar/tavangar_simple/decals_dr7_results/results_nside_32_5145.csv /home/s1/tavangar/tavangar_simple/decals_dr7_log/results_nside_32_5145.log
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

	Real time :			17.10 sec.
	CPU time :			1.53 sec.
	CPU percentage :		21%
	Max Memory :			279200 KB
	Average Memory :		0 KB

The output (if any) is above this job summary.
